# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 835ca5d84cdecac03f29c6f058ce1453c4e7de7eb57900dcec16b559dacea24864496560b4b3eba822f33481980039ee201c8954463cc8df2e0911ce22ef6d15

test:
  secret_key_base: 6f3f4553d22c911225e9079402389f4d71923290d79b0f8e7296c751b4e59d35dfe7f7b5ba8916fb575cfeda5380d4faeda242c0c0138da05beed5002b5a1913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
